- name: Flutter action
  uses: subosito/flutter-action@v2.10.0
  
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
     - run: flutter build windows
