on:
  push:
     branches: [ dev ]
name: Generate server documentations
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install json-schema-static-docs
    - run: touch index.js
    - working-directory: ./documentation/server
      run: |
        echo "const JsonSchemaStaticDocs = require('json-schema-static-docs');

        (async () => {
          let jsonSchemaStaticDocs = new JsonSchemaStaticDocs({
            inputPath: 'schema',
            outputPath: 'docs',
            ajvOptions: {
              allowUnionTypes: true,
            },
          });
          await jsonSchemaStaticDocs.generate();
          console.log('Documents generated.');
        })();" > index.js
    - run: node index.js
      working-directory: ./documentation/server
    - run: |
        echo "function Link(el)
        el.target = string.gsub(el.target,'.md', '.html')
        return el
        end" > links-to-html.lua
      working-directory: ./documentation/server
    - run: sudo apt-get install pandoc
      working-directory: ./documentation/server
    - run : echo $(curl https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/github-markdown-light.css) | sed "${s//.markdown-/}" > markdowncss.css
      working-directory: ./documentation/server/docs
    - run: for i in $(find docs -name "*.md"); do pandoc -f markdown -t html -s "$i" --css markdowncss.css --lua-filter=links-to-html.lua > "${i/.md/.html}"; done;
      working-directory: ./documentation/server
    - run : find docs -name "*.md" | xargs rm
      working-directory: ./documentation/server
    - uses: actions/upload-artifact@v3
      with:
          name: documentation
          path: ./documentation/server/docs
    
